config/routes.rb
Ahreloco::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "users/index"
  root to: "home#index"


  match 'auth/youtube/callback' => 'sessions#create'
  match 'auth/failure' => 'sessions#failure'
  match "/signout" => "sessions#destroy", :as => :signout

  resources :users, only: [:show, :index]  do
    get :profile
  end

  resources :beta_users, only: [:new, :create, :show] 

  resources :home, only: [:index]
  resources :team, only: [:index]
  resources :playlist, only: [:index]

  resources :videos , only: [:index,:new, :create] do
    new do
       post :upload
       get  :save_video
    end
  end
    
  resources :comments, only: [:index, :create]
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  belongs_to :playlist
  scope :top_today, order('arl_views_today DESC')
  scope :top_week, order('arl_views_week DESC')
  scope :top_month, order('arl_views_month DESC')
  scope :with_program, joins(user:[:programs])
  scope :from_community, joins("INNER JOIN \"users\" ON \"users\".\"id\" = \"videos\".\"user_id\" FULL OUTER JOIN \"programs_users\" ON \"programs_users\".\"user_id\" = \"users\".\"id\"")
    .where("\"programs_users\".\"user_id\" IS NULL" )

  scope :latest_published, order('published_at DESC')

  attr_accessible :video_id, :title, :is_complete, :likes, :dislikes, :playlist_id,
    :rater_count, :published_at, :arl_views_today, :arl_views_week, :arl_views_month,:view_count,
    :user_id, :description


  def update_with(video)
    params = self.class.parsed_attributes(video)
    update_attributes(params)
  end

  def small_thumb
    "http://i2.ytimg.com/vi/#{video_id}/mqdefault.jpg"
  end

  def big_thumb
    "http://i2.ytimg.com/vi/#{video_id}/hqdefault.jpg"
  end

  def hit_it!
    update_attributes( arl_views_today: arl_views_today + 1,
      arl_views_week: arl_views_week + 1, arl_views_month: arl_views_month + 1)
  end

  # to check: playlist id included in the video?
  def self.parsed_attributes(video)
    pa = {
      published_at: video.published_at,
      view_count: video.view_count,
      video_id: video.unique_id,
      title: video.title
    }
    if video.rating
      pa.merge({
        likes: video.rating.likes,
        dislikes: video.rating.dislikes,
        rater_count: video.rating.rater_count
      })
    end
    pa
  end

  def self.last_week_winner
  end
end

app/controllers/videos_controller.rb
class VideosController < InheritedResources::Base
  before_filter :authenticate_user!

  def upload
    arl_manager.playlist
    @video = Video.create(params[:video].merge({playlist_id: Playlist.last.id,
      user_id: current_user.id, published_at: Date.today }))

    if @video
      @upload_info = arl_manager.client.upload_token(options_for(@video),
       save_video_new_video_url(video_id: @video.id))
    else
      respond_to do |format|
        format.html { render :new }
      end
    end
  end

  def save_video
    @video = Video.find(params[:video_id])
    if params[:status].to_i == 200
      @video.update_attributes(video_id: params[:id].to_s, is_complete: 'true')
      arl_manager.add_video_to_week_playlist @video
      #Video.delete_incomplete_videos
    else
      #Video.delete_video(@video)
    end

    redirect_to user_path(current_user), notice: 'video successfully uploaded'
  end

  protected
  def collection
    @videos ||= end_of_association_chain.latest_published.page(params[:page])
  end

  private
  def options_for(video)
    opts = {title: video.title,
            description: video.description,
            category: 'People',
            keywords: [ 'ahreloco.tv', 'ahreloco', 'ah re loco', 'concurso semanal',
              'concurso', 'red social', 'comunidad', 'youtubers', 'youtube', 'Rate',
              'Subscribers' ],
            private: false,
            list: "denied"
          }
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_conquest_list.html.haml
- if videos
  .row-fluid.videos
    -videos.each do |video|
      .row-fluid.video
        .span5
          = image_tag(video.small_thumb)
        .span7
          %p
            %h4
              = link_to video.title, user_path(video.user, video_id: video.id)
            %em.muted
              de
              = link_to video.user.username, user_path(video.user)

app/views/videos/_home_list.html.haml
%table.table.table-condensed
  -videos.each_with_index do |v,i|
    %tr
      %td= i+1
      %td
        =link_to truncate(v.title,length: 50), user_path(v.user, video_id: v.id)
        %small.muted
          de
          =link_to v.user.username, user_path(v.user, video_id: v.id)

app/views/videos/_list.html.haml
- if videos
  .row-fluid.videos
    -videos.each do |video|
      .row-fluid.video
        .span2
          = image_tag(video.thumbnails.first[:url]) if video.thumbnails
        .span10
          %p
            %h4
              = link_to video.title, user_path(video.user, video_id: video.id)
            %em.muted
              de
              = link_to video.user.username, user_path(video.user)
          %h5
            vistas:
            = video.view_count

app/views/videos/new.html.haml
%center
  %h1
    Bienvenido al concurso semanal de AhReLoco.Tv

%ul
  %li
    %h4
      Para participar tienes que subir un video y compartirlo con todos tus amigos.
  %li
    %h4
      Ganara el video que tenga mas visitas al terminar la semana.
  %li
    %h4
      El video ganador aparecera en la Home de AhReLoco.tv junto a los ultimos videos de nuestros programas mas vistos y en nuestra pagina de facebook para que puedas hacer crecer y conocer tu canal de Youtube.
%hr
.row-fluid
  .span6
    %h3
      Datos del video:
    = form_for @video, url: upload_new_video_path, html: { class: 'form-horizontal' } do |f|
      .control-group
        %label.control-label
          Titulo
        .controls
          = f.text_field :title, placeholder: 'Titulo del video', class: 'text_field',
            required: true
      .control-group
        %label.control-label
          Descripcion
        .controls
          = f.text_area :description, placeholder: 'Descripcion del video', class: 'text_field',
            cols: 40, rows: 10, required: true
      .control-group
        .controls
          = f.submit 'Acepto terminos y condiciones!', class: 'btn btn-success'

  .span6.well
    %h3
      terminos y condiciones:

    %textarea{'cols' => 40, 'rows' => 10}
      El concurso se llevara acabo de domingo a domingo, teniendo tiempo de enviar videos hasta el jueves de esa semana en cuestion. Los videos no pueden infligir ninguna ley de copyright ni contener pornografia. El contenido debe ser exclusivo para cada concurso y no puede ser resubido a otro canal de YouTube. Los datos de contacto deber ser reales y en caso de no cumplir alguna de estas clausulas se tomaran las medidas necesarias segun YouTube Argentina disponga sobre el canal que participo del concurso, liberando al canal de AhReLocoTv de toda culpa y cargo. A efectos del presente, el usuario, al participar del concurso, acepta ceder los derechos de los contenidos subidos al canal de AhrelocoTV y todas las resubidas que existan en la plataforma de YouTube. El usuario acepta que Faro latino en representacion de AhrelocoTV, incluya publicidades en los videos. El ganador  sera el video con mas vistas al finalizar la semana y en consecuencia aparecera su video como recomendado en la pagina principal del sitio AhReLoco.Tv entre los programas mas importantes del sitio, como asi tambiwn en la pagina de Facebook de AhReLocoTv por el periodo de una semana hasta el proximo ganador.

app/views/videos/upload.html.haml
%h2.title
  nuevo video
%p
  Step 2: subi el video para concursar.
= form_tag @upload_info[:url], multipart: true do
  = hidden_field_tag :token, @upload_info[:token]
  = label_tag :file
  = file_field_tag :file
  = submit_tag 'Subir video', class: 'btn',disable_with: 'Subiendo...', id: 'upload-video'