config/routes.rb
Ahreloco::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "users/index"
  root to: "home#index"


  match 'auth/youtube/callback' => 'sessions#create'
  match 'auth/failure' => 'sessions#failure'
  match "/signout" => "sessions#destroy", :as => :signout

  resources :users, only: [:show, :index]  do
    get :profile
  end

  resources :beta_users, only: [:new, :create, :show] 

  resources :home, only: [:index]
  resources :team, only: [:index]
  resources :playlist, only: [:index]

  resources :videos , only: [:index,:new, :create] do
    new do
       post :upload
       get  :save_video
    end
  end
    
  resources :comments, only: [:index, :create]
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to home_index_path, class: 'brand' do
  %i.icon-home.icon-white
  =image_tag 'logo.png'
%ul.nav
  %li.dropdown.programs
    %a.dropdown-toggle.programs-btn(href="#")
      Programas
      %b.caret
    %ul.dropdown-menu
      - Program.order(:name).all.each do |p|
        %li.program
          %a
            = image_tag p.avatar_url
            =  p.name
            %b.caret
        .channels.hide
          -p.users.each do |u|
            %li.channel= link_to u.username, user_path(u)

%ul.nav.pull-right
  - if user_signed_in?
    %li.dropdown
      %a.dropdown-toggle(href="#" data-toggle="dropdown")
        %i.icon-film.icon-white
        Concurso semanal!
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to new_video_path do
            %i.icon-upload
            Subi tu video

    %li.divider-vertical
    %li
      = link_to current_user, class: 'image', id: 'username' do
        = image_tag current_user.avatar_url, width: 30, height: 25
        = current_user.username
    %li.divider-vertical
    %li.dropdown
      %a.dropdown-toggle(href="#" data-toggle="dropdown")
        %i.icon-cog.icon-white
      %ul.dropdown-menu
        %li
        /  = link_to current_user do
        /    %i.icon-user
        /    Editar mi perfil
        %li
          = link_to signout_path do
            %i.icon-off
            Cerrar sesion

  -  else
    %li
      = link_to "Loggeate con tu cuenta de youtube", '/auth/youtube'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Ahreloco"
      %meta{:content => content_for?(:description) ? yield(:description) : "Ahreloco", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}", :data => page_attributes }

    .overlay
      #loading
    = analytics_init if Rails.env.production?

    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
          %footer.row
            .container-footer.span12
              .container-footer-inner
                %dl
                  %dt
                    Ahreloco.tv
                %dl
                  %dt
                    Ayuda
                  %dd
                    = link_to('Preguntas Frecuentes', '#')
                  %dd
                    = mail_to('bonzofenix@gmail.com','Contactanos')
                %dl
                  %dt
                    Comunidad
                  %dd
                    = link_to('Facebook', "http://www.facebook.com/ahrelocotv", rel: 'nofollow')
                  %dd
                    = link_to('Twitter',"https://twitter.com/ahrelocotv", rel: 'nofollow')
                  %dd
                    = link_to('Youtube','http://youtube.com/user/ahrelocotv', rel: 'nofollow')
                .row-fluid
                  .span12
                    .pull-right
                      %h6
                        Copyright 2013 Ahreloco.tv. Todos los derechos reservados.
                        /%br
                        /Desarrollado por
                        /=link_to('Bonzofenix.', 'http://bonzofenix.github.io/', class: 'red')
      / ! end of .container
    / ! end of #main